source "https://rubygems.org"
gem "jekyll"
gem "jekyll-paginate-v2"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "webrick"
gem "premonition"
gem "h2o-ac-jekyll-extlinks"
gem "nokogiri"
gem 'wdm', '>= 0.1.0'